"""Readable summary and the one chart, both generated from results.json."""

import json

GRADES = ("v=0.00", "v=0.25", "v=0.50", "v=0.75", "v=0.90", "v=1.00")
DETECTORS = ("baseline 1: rolling volume", "baseline 2: rolling decline",
             "baseline 3: combined", "GRAPH: fanout vs overlap")
SHORT = {"baseline 1: rolling volume": "volume",
         "baseline 2: rolling decline": "decline",
         "baseline 3: combined": "combined",
         "GRAPH: fanout vs overlap": "GRAPH"}


def _decline_axis(results):
    """Observed attack decline rate per grade, from the cost stage."""
    fe = results["cost"]["frozen_excess"][DETECTORS[0]]
    return [fe[g]["attack_decline_pct"] for g in GRADES]


def write_summary(results, meta, path):
    d = results["detector_sweep"]
    dec = _decline_axis(results)
    L = []
    a = L.append
    a("# Results\n")
    a("Generated by `python -m pipeline.evaluate`. Every number here comes from")
    a("`results.json`. Nothing in this file is typed by hand.\n")
    a(f"- commit `{meta['git_commit'][:12]}`"
      f"{' (working tree dirty)' if meta['git_dirty'] else ''}")
    a(f"- seed {meta['seed']}, {meta['days']} days, {meta['actors']:,} actors")
    a(f"- python {meta['python']}, "
      + ", ".join(f"{k} {v}" for k, v in sorted(meta["packages"].items())))
    a(f"- results.json sha256 `{meta['results_sha256'][:16]}`")
    a(f"- wall time {meta['wall_time_seconds']/60:.1f} min\n")

    a("## The central result: PR AUC against observed decline rate\n")
    a("![PR AUC against observed decline rate](pr_auc_vs_decline.png)\n")
    a("| detector | " + " | ".join(f"{x:.1f}%" for x in dec) + " |")
    a("|---" * 7 + "|")
    for det in DETECTORS:
        a(f"| {det} | "
          + " | ".join(f"{d['pr_auc'][det][g]:.4f}" for g in GRADES) + " |")
    a("")

    a("### Recall\n")
    a("| detector | " + " | ".join(GRADES) + " |")
    a("|---" * 7 + "|")
    for det in DETECTORS:
        a(f"| {det} | "
          + " | ".join(f"{d['recall'][det][g]:.4f}" for g in GRADES) + " |")
    a("")

    a("### Bursts missed entirely (of 2 in the test split)\n")
    a("| detector | " + " | ".join(GRADES) + " |")
    a("|---" * 7 + "|")
    for det in DETECTORS:
        a(f"| {det} | "
          + " | ".join(str(d["bursts_missed"][det][g]) for g in GRADES) + " |")
    a("")

    a("## Cost: the price of not adapting\n")
    a("Excess rupees from freezing the threshold at the v=0.00 money optimum.\n")
    a("| detector | " + " | ".join(GRADES) + " |")
    a("|---" * 7 + "|")
    for det in DETECTORS:
        fe = results["cost"]["frozen_excess"][det]
        a(f"| {det} | "
          + " | ".join(f"{fe[g]['excess_rupees']:,.0f}" for g in GRADES) + " |")
    a("")
    a("| detector | F1 threshold | money threshold | gap (Rs) | gap % |")
    a("|---|---|---|---|---|")
    for det in DETECTORS:
        op = results["cost"]["operating_points"][det]
        a(f"| {det} | {op['f1_threshold']:.4f} | {op['money_threshold']:.4f} | "
          f"{op['gap_rupees']:,.0f} | {op['gap_pct']:.2f}% |")
    a("")

    a("## Streaming against batch\n")
    s = results["streaming"]
    a(f"Reproduces batch exactly: **{s['exact']}**. "
      f"Alerts batch {s['alerts']['batch']}, stream {s['alerts']['stream']}, "
      f"identical {s['alerts']['identical']}.\n")
    a("| detector | events | mismatches | max abs diff |")
    a("|---|---|---|---|")
    for det in DETECTORS:
        e = s["equivalence"][det]
        a(f"| {det} | {e['events']:,} | {e['mismatches']} | {e['max_abs_diff']:g} |")
    a("")
    # Throughput lives in run_meta, not results.json: it is a stopwatch reading
    # and it varied 453 to 553 events/sec between two runs of identical code.
    perf = meta.get("performance", {})
    if "streaming.throughput_events_per_sec" in perf:
        a(f"Throughput {perf['streaming.throughput_events_per_sec']:,.0f} "
          f"events/sec, {perf['streaming.throughput_ms_per_event']:.3f} ms per "
          f"event. Measured, not reproducible: it moves with machine load, "
          f"which is why it is recorded in `run_meta.json` and not here.\n")
    a("| events | peak KiB | max window events |")
    a("|---|---|---|")
    for m in s["memory"]:
        a(f"| {m['events']:,} | {m['peak_kib']:.1f} | {m['max_window_events']} |")
    a("")

    a("## Acceptance tests\n")
    tests = sorted({t for g in results["acceptance"].values() for t in g})
    a("| test | " + " | ".join(GRADES) + " |")
    a("|---" * 7 + "|")
    for t in tests:
        cells = []
        for g in GRADES:
            r = results["acceptance"].get(g, {}).get(t)
            cells.append("PASS" if r and r["pass"] else ("FAIL" if r else "-"))
        a(f"| {t} | " + " | ".join(cells) + " |")
    a("")

    a("## Ring detector, patched population\n")
    a("| detector | precision | recall | PR AUC |")
    a("|---|---|---|---|")
    for name, r in results["ring"].items():
        if isinstance(r, dict) and "pr_auc" in r:
            a(f"| {name} | {r['precision']:.4f} | {r['recall']:.4f} | "
              f"{r['pr_auc']:.4f} |")
    a("")

    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L))


def write_chart(results, path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    d = results["detector_sweep"]["pr_auc"]
    x = _decline_axis(results)
    style = {"baseline 1: rolling volume": ("#8c8c8c", "o", "--"),
             "baseline 2: rolling decline": ("#c0392b", "s", "-"),
             "baseline 3: combined": ("#e08a1e", "^", "-."),
             "GRAPH: fanout vs overlap": ("#1f6fb4", "D", "-")}

    fig, ax = plt.subplots(figsize=(8.6, 5.4), dpi=160)
    for det in DETECTORS:
        c, mk, ls = style[det]
        y = [d[det][g] for g in GRADES]
        ax.plot(x, y, marker=mk, linestyle=ls, color=c, linewidth=2.0,
                markersize=6, label=SHORT[det])

    ax.invert_xaxis()          # the attacker evades left to right
    ax.set_xlabel("Observed attack decline rate (%)  ->  attacker evades")
    ax.set_ylabel("PR AUC (test split, threshold-free)")
    ax.set_title("Detector performance as card testing evades\n"
                 "thresholds frozen at v=0.00, four detectors, six grades",
                 fontsize=11)
    ax.set_ylim(0.0, 1.02)
    ax.grid(alpha=0.25, linestyle=":")
    ax.legend(loc="lower left", frameon=True, framealpha=0.95)

    # Annotations anchored in axes fraction so the text cannot run off the edge
    # when the data range changes. The x axis is inverted, so data-space offsets
    # point the wrong way and are not used here.
    lo = d["baseline 2: rolling decline"]["v=1.00"]
    ax.annotate(f"decline baseline collapses\nto {lo:.4f}",
                xy=(x[-1], lo), xycoords="data",
                xytext=(0.60, 0.30), textcoords="axes fraction",
                fontsize=9, color="#c0392b", ha="left", va="center",
                arrowprops=dict(arrowstyle="->", color="#c0392b", lw=1.2,
                                connectionstyle="arc3,rad=-0.15"))
    g_flat = d["GRAPH: fanout vs overlap"]["v=1.00"]
    ax.annotate(f"graph holds {g_flat:.4f}\nat every evasive grade",
                xy=(x[-1], g_flat), xycoords="data",
                xytext=(0.46, 0.66), textcoords="axes fraction",
                fontsize=9, color="#1f6fb4", ha="left", va="center",
                arrowprops=dict(arrowstyle="->", color="#1f6fb4", lw=1.2,
                                connectionstyle="arc3,rad=0.15"))
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
